###
PATCH http://localhost:5000/kendaraan/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjo5LCJyb2xlIjoxLCJpYXQiOjE2Nzk0NDI4Njl9.BexfU9wcHEAKIM8gO5QJbNoP1_LwVXV6Ou_ITJsIXhI

{
    "id_kendaraan": 2,
    "nama_kendaraan": "Kol Series Nopol N 99 LGX",
    "jenis": "pribadi",
    "tipe": "angkutan orang",
    "id_ps": "",
    "ketersediaan": 1,
    "nama_ps": "PT. Warmindar (Warung Peminjaman Kendaraan)"
}